spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:mem:mediconnect}
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
  docker:
    compose:
      lifecycle-management: start-only
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      DoctorIdValid: DOCTOR_ID_VALID
      ScheduleSAscheduleIdUnique: SCHEDULE_SASCHEDULE_ID_UNIQUE
      PatientIdValid: PATIENT_ID_VALID
springdoc:
  pathsToMatch: /api/**

vegs:
  photo-baseurl: ${PHOTO_BASEURL:https://mediconnect-latest.onrender.com}